server:
  port: ${PORT:8082}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  jpa:
    deferDatasourceInitialization: true
    hibernate:
      ddlAuto: update
  datasource:
    url: jdbc:mysql://localhost:3306/examen_back
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
